// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.14
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:366


#include "msgTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "msgTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for msg::MessageTypeSupport.

msg::MessageTypeSupport_ptr
TAO::Objref_Traits<msg::MessageTypeSupport>::duplicate (
    msg::MessageTypeSupport_ptr p)
{
  return msg::MessageTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<msg::MessageTypeSupport>::release (
    msg::MessageTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

msg::MessageTypeSupport_ptr
TAO::Objref_Traits<msg::MessageTypeSupport>::nil (void)
{
  return msg::MessageTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<msg::MessageTypeSupport>::marshal (
    const msg::MessageTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



msg::MessageTypeSupport::MessageTypeSupport (void)
{}

msg::MessageTypeSupport::~MessageTypeSupport (void)
{
}

msg::MessageTypeSupport_ptr
msg::MessageTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageTypeSupport::_duplicate (
      dynamic_cast<MessageTypeSupport_ptr> (_tao_objref));
}

msg::MessageTypeSupport_ptr
msg::MessageTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageTypeSupport::_duplicate (
      dynamic_cast<MessageTypeSupport_ptr> (_tao_objref));
}

msg::MessageTypeSupport_ptr
msg::MessageTypeSupport::_nil (void)
{
  return 0;
}

msg::MessageTypeSupport_ptr
msg::MessageTypeSupport::_duplicate (MessageTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
msg::MessageTypeSupport::_tao_release (MessageTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
msg::MessageTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:msg/MessageTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* msg::MessageTypeSupport::_interface_repository_id (void) const
{
  return "IDL:msg/MessageTypeSupport:1.0";
}

::CORBA::Boolean
msg::MessageTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for msg::MessageDataWriter.

msg::MessageDataWriter_ptr
TAO::Objref_Traits<msg::MessageDataWriter>::duplicate (
    msg::MessageDataWriter_ptr p)
{
  return msg::MessageDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<msg::MessageDataWriter>::release (
    msg::MessageDataWriter_ptr p)
{
  ::CORBA::release (p);
}

msg::MessageDataWriter_ptr
TAO::Objref_Traits<msg::MessageDataWriter>::nil (void)
{
  return msg::MessageDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<msg::MessageDataWriter>::marshal (
    const msg::MessageDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



msg::MessageDataWriter::MessageDataWriter (void)
{}

msg::MessageDataWriter::~MessageDataWriter (void)
{
}

msg::MessageDataWriter_ptr
msg::MessageDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageDataWriter::_duplicate (
      dynamic_cast<MessageDataWriter_ptr> (_tao_objref));
}

msg::MessageDataWriter_ptr
msg::MessageDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageDataWriter::_duplicate (
      dynamic_cast<MessageDataWriter_ptr> (_tao_objref));
}

msg::MessageDataWriter_ptr
msg::MessageDataWriter::_nil (void)
{
  return 0;
}

msg::MessageDataWriter_ptr
msg::MessageDataWriter::_duplicate (MessageDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
msg::MessageDataWriter::_tao_release (MessageDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
msg::MessageDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:msg/MessageDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* msg::MessageDataWriter::_interface_repository_id (void) const
{
  return "IDL:msg/MessageDataWriter:1.0";
}

::CORBA::Boolean
msg::MessageDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for msg::MessageDataReader.

msg::MessageDataReader_ptr
TAO::Objref_Traits<msg::MessageDataReader>::duplicate (
    msg::MessageDataReader_ptr p)
{
  return msg::MessageDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<msg::MessageDataReader>::release (
    msg::MessageDataReader_ptr p)
{
  ::CORBA::release (p);
}

msg::MessageDataReader_ptr
TAO::Objref_Traits<msg::MessageDataReader>::nil (void)
{
  return msg::MessageDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<msg::MessageDataReader>::marshal (
    const msg::MessageDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



msg::MessageDataReader::MessageDataReader (void)
{}

msg::MessageDataReader::~MessageDataReader (void)
{
}

msg::MessageDataReader_ptr
msg::MessageDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageDataReader::_duplicate (
      dynamic_cast<MessageDataReader_ptr> (_tao_objref));
}

msg::MessageDataReader_ptr
msg::MessageDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageDataReader::_duplicate (
      dynamic_cast<MessageDataReader_ptr> (_tao_objref));
}

msg::MessageDataReader_ptr
msg::MessageDataReader::_nil (void)
{
  return 0;
}

msg::MessageDataReader_ptr
msg::MessageDataReader::_duplicate (MessageDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
msg::MessageDataReader::_tao_release (MessageDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
msg::MessageDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:msg/MessageDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* msg::MessageDataReader::_interface_repository_id (void) const
{
  return "IDL:msg/MessageDataReader:1.0";
}

::CORBA::Boolean
msg::MessageDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

